image: Visual Studio 2019
version: "0.1.0-ci.{build}"
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "false")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_BUILD_VERSION+sha.$($env:APPVEYOR_REPO_COMMIT.Substring(0, 9))"
      } else {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
skip_branch_with_pr: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: "{version}"
  package_version: "{version}"
install:
  - appveyor-retry dotnet restore -v Minimal
  - appveyor-retry choco install codecov
configuration: Release
build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
after_test:
  - codecov -f "tests/GalaScriptTests/coverage.opencover.xml"
deploy:
  - provider: NuGet
    name: MyGet
    server: https://www.myget.org/F/galaengine/api/v2/package
    symbol_server: https://www.myget.org/F/galaengine/symbols/api/v2/package
    api_key:
      secure: 9EKvm3W60xQMcta7WZW0BISOOISgd1535xd3ie/D/uLcuFAjzDLBRzn2myEcd5xC
    on:
      branch: develop
  - provider: NuGet
    name: NuGet
    api_key:
      secure: oYRL+tdfczOc3hZH5CxipwwtvIXl+68XI375/ZBbty6/MvaGdikD1oeC9wkYwkn9
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: GitHub Release
    auth_token:
      secure: IApJWoucWEA6qjZn1atyOtaEMbBJVMcs8r4AeTwX3yOPWYK76w6VzOpzG+eTainp
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
